name: Unpack repo ZIP

on:
  workflow_dispatch:     # İstersen elle "Run workflow" ile çalıştır
  push:
    paths:
      - "*.zip"          # Zip push edilince otomatik çalışsın

permissions:
  contents: write        # Commit/push için gerekli

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip into repo root
        env:
          ZIP_NAME: sofascore_like_backend_and_app_v5_2_full_railway_fixed.zip
        run: |
          if [ ! -f "$ZIP_NAME" ]; then
            echo "ZIP not found: $ZIP_NAME"
            ls -la
            exit 1
          fi
          rm -rf temp_unzip && mkdir -p temp_unzip
          unzip -o "$ZIP_NAME" -d temp_unzip
          shopt -s dotglob
          mv -f temp_unzip/* .
          shopt -u dotglob
          rm -rf temp_unzip
          rm -f "$ZIP_NAME"

      - name: Commit & push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "Unpack ZIP into repository" || echo "No changes to commit"
          git push
name: Unpack ZIP to repo
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files
        run: ls -la
      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip
      - name: Unzip and move
        run: |
          unzip -o sofascore_like_backend_and_app_v5_2_full.zip -d extracted
          shopt -s dotglob
          cp -r extracted/* .
          rm -rf extracted sofascore_like_backend_and_app_v5_2_full.zip
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          message: "Unpack ZIP to repo (backend + app)"
          default_author: github_actions
